[Feature] Support new integration token format
codex-team/hawk.javascript pull request #79
Opened 2021-08-24 00:02 UTC by ilyamore88

I added support of the new integration token format.

2021-08-24 00:28 UTC, neSpecc approved these changes

2021-08-24 17:22 UTC, talyguryn commented on package.json
> +    "hawk.types": "codex-team/hawk.types"
это будет нормально резолвиться в докерах?

2021-08-24 17:25 UTC, ilyamore88 commented on package.json
> +    "hawk.types": "codex-team/hawk.types"
Да.

2021-08-25 14:06 UTC, talyguryn requested changes

2021-08-25 14:06 UTC, talyguryn commented on package.json
> +    "hawk.types": "codex-team/hawk.types"
https://www.npmjs.com/package/@hawk.so/types

2021-08-25 14:19 UTC, talyguryn approved these changes

2021-08-25 14:20 UTC, merged